'use client';

import { createContext, useContext, type ReactNode } from 'react';

// --- Types ---

/**
 * Type alias for theme message trees — a deeply nested record of translation strings.
 */
export type ThemeMessageTree = Record<string, unknown>;

/**
 * Map of locale → message tree for a single theme.
 */
export type ThemeMessagesByLocale = Record<string, ThemeMessageTree>;

/**
 * Map of themeId → locale → message tree.
 * Generated by the host application (themes-prepare script).
 */
export type ThemeI18nRegistry = Record<string, ThemeMessagesByLocale>;

// --- Helper Functions ---

/**
 * Resolves messages for a given theme and locale from the registry.
 * Falls back to defaultLocale if the specific locale is missing.
 */
export function resolveThemeMessages(
    registry: ThemeI18nRegistry,
    themeId: string | null | undefined,
    locale: string,
    defaultLocale: string = 'en'
): ThemeMessageTree {
    if (!themeId) return {};

    const themeMessages = registry[themeId];
    if (!themeMessages) return {};

    return themeMessages[locale] ?? themeMessages[defaultLocale] ?? {};
}

// --- Context ---

type ThemeI18nContextValue = {
    registry: ThemeI18nRegistry;
    locale: string;
    defaultLocale: string;
};

const ThemeI18nContext = createContext<ThemeI18nContextValue>({
    registry: {},
    locale: 'en',
    defaultLocale: 'en'
});

// --- Provider ---

/**
 * Provides the theme i18n registry and current locale to the component tree.
 * This should be rendered by the host application, passing in its generated registry.
 */
export function ThemeI18nProvider({
    registry,
    locale,
    defaultLocale = 'en',
    children
}: {
    registry: ThemeI18nRegistry;
    locale: string;
    defaultLocale?: string;
    children: ReactNode;
}) {
    return (
        <ThemeI18nContext.Provider value={{ registry, locale, defaultLocale }}>
            {children}
        </ThemeI18nContext.Provider>
    );
}

// --- Hook ---

/**
 * Hook to access translation messages for a specific theme.
 * Accesses the registry provided by ThemeI18nProvider.
 *
 * @param themeId - The ID of the theme (e.g., 'theme.pilot.admin').
 * @returns The message tree for the current locale.
 */
export function useThemeMessages(themeId?: string | null): ThemeMessageTree {
    const { registry, locale, defaultLocale } = useContext(ThemeI18nContext);
    return resolveThemeMessages(registry, themeId, locale, defaultLocale);
}
