/**
 * Route registry entry point - imported by proxy.ts to ensure all routes
 * are registered (and area proxy defaults configured) before any request.
 *
 * core/routes.ts imports '@/lib/routing/area-setup' as its first import,
 * which calls configureAreaDefaults({ admin: [proxyAdmin], dashboard: [proxyAuth] })
 * before any RouteAdmin/RouteDashboard calls execute.
 *
 * HOW TO ADD A MODULE'S ROUTES:
 * Declare `routesEntry` in the module's module.json and run `pnpm modules:prepare`.
 * The generated import lands in ./all-routes.generated, and module routes.ts files
 * do not need to import '@/lib/routing/area-setup'.
 *
 * @example
 * // module.json
 * // { "routesEntry": "src/routes.ts" }
 * // pnpm modules:prepare
 */

// Core routes (includes area-setup as its first import)
import '@/core/routes';

// Auto-generated module routes - regenerated by pnpm modules:prepare
// Declare routesEntry in a module's module.json to be included here.
import './all-routes.generated';
