// Auto-generated by pnpm i18n:prepare. Do not edit.
import type { GlobalMessages } from './messages/global';
import type { AdminMessages } from './messages/admin';
import type { DashboardMessages } from './messages/dashboard';
import type { LoginMessages } from './messages/login';
import en_global from './locales/en/global';
import es_global from './locales/es/global';
import en_admin from './locales/en/admin';
import es_admin from './locales/es/admin';
import en_dashboard from './locales/en/dashboard';
import es_dashboard from './locales/es/dashboard';
import en_login from './locales/en/login';
import es_login from './locales/es/login';

export const coreMessagesByArea = {
  global: {
    en: en_global,
    es: es_global,
  },
  admin: {
    en: en_admin,
    es: es_admin,
  },
  dashboard: {
    en: en_dashboard,
    es: es_dashboard,
  },
  login: {
    en: en_login,
    es: es_login,
  },
} satisfies {
  global: Record<string, GlobalMessages>;
  admin: Record<string, AdminMessages>;
  dashboard: Record<string, DashboardMessages>;
  login: Record<string, LoginMessages>;
};
