import type { ComponentType } from 'react';
import type { ThemeConfig } from './config';

export type CodeRegistryThemeEntry = {
  themeId: string;
  configImport: (() => Promise<{ default: ThemeConfig }>) | null;
  providerImport: (() => Promise<{ default: ComponentType<{ children: React.ReactNode }> }>) | null;
  templates: Record<string, () => Promise<{ default: ComponentType<any> }>>;
};

export const THEME_CODE_REGISTRY: Record<string, CodeRegistryThemeEntry> = {
  "theme.first.backoffice": {
    themeId: "theme.first.backoffice",
    configImport: () => import("../../themes/first-backoffice/config"),
    providerImport: () => import("../../themes/first-backoffice/config").then(m => ({ default: m.default?.Provider ?? (({ children }: any) => children) })),
    templates: {
      "layout.admin.app-config.shell": () => import("../../themes/first-backoffice/templates/admin/layout.admin.app-config.shell"),
      "layout.admin.shell": () => import("../../themes/first-backoffice/templates/admin/layout.admin.shell"),
      "layout.dashboard.shell": () => import("../../themes/first-backoffice/templates/dashboard/layout.dashboard.shell"),
      "layout.private.header": () => import("../../themes/first-backoffice/templates/layout.private.header"),
      "layout.private.shell": () => import("../../themes/first-backoffice/templates/layout.private.shell"),
      "page.admin.app-config.email": () => import("../../themes/first-backoffice/templates/admin/page.admin.app-config.email"),
      "page.admin.app-config.general": () => import("../../themes/first-backoffice/templates/admin/page.admin.app-config.general"),
      "page.admin.app-config.home": () => import("../../themes/first-backoffice/templates/admin/page.admin.app-config.home"),
      "page.admin.app-config.payment-methods": () => import("../../themes/first-backoffice/templates/admin/page.admin.app-config.payment-methods"),
      "page.admin.app-config.theme": () => import("../../themes/first-backoffice/templates/admin/page.admin.app-config.theme"),
      "page.admin.home": () => import("../../themes/first-backoffice/templates/admin/page.admin.home"),
      "page.admin.logs": () => import("../../themes/first-backoffice/templates/admin/page.admin.logs"),
      "page.admin.orders": () => import("../../themes/first-backoffice/templates/admin/page.admin.orders"),
      "page.admin.orders.create": () => import("../../themes/first-backoffice/templates/admin/page.admin.orders.create"),
      "page.admin.orders.edit": () => import("../../themes/first-backoffice/templates/admin/page.admin.orders.edit"),
      "page.admin.payments": () => import("../../themes/first-backoffice/templates/admin/page.admin.payments"),
      "page.admin.subscriptions.create": () => import("../../themes/first-backoffice/templates/admin/page.admin.subscriptions.create"),
      "page.admin.subscriptions.edit": () => import("../../themes/first-backoffice/templates/admin/page.admin.subscriptions.edit"),
      "page.admin.subscriptions.templates": () => import("../../themes/first-backoffice/templates/admin/page.admin.subscriptions.templates"),
      "page.admin.suscriptions": () => import("../../themes/first-backoffice/templates/admin/page.admin.suscriptions"),
      "page.admin.suscriptions.organization.edit": () => import("../../themes/first-backoffice/templates/admin/page.admin.suscriptions.organization.edit"),
      "page.admin.suscriptions.user.edit": () => import("../../themes/first-backoffice/templates/admin/page.admin.suscriptions.user.edit"),
      "page.admin.user.detail": () => import("../../themes/first-backoffice/templates/admin/page.admin.user.detail"),
      "page.admin.users": () => import("../../themes/first-backoffice/templates/admin/page.admin.users"),
      "page.dashboard.activity": () => import("../../themes/first-backoffice/templates/dashboard/page.dashboard.activity"),
      "page.dashboard.activity.loading": () => import("../../themes/first-backoffice/templates/dashboard/page.dashboard.activity.loading"),
      "page.dashboard.general": () => import("../../themes/first-backoffice/templates/dashboard/page.dashboard.general"),
      "page.dashboard.home": () => import("../../themes/first-backoffice/templates/dashboard/page.dashboard.home"),
      "page.dashboard.security": () => import("../../themes/first-backoffice/templates/dashboard/page.dashboard.security"),
      "page.dashboard.subscriptions": () => import("../../themes/first-backoffice/templates/dashboard/page.dashboard.subscriptions"),
      "page.login.admin": () => import("../../themes/first-backoffice/templates/page.login.admin"),
      "page.login.signup": () => import("../../themes/first-backoffice/templates/page.login.signup"),
      "page.login.user": () => import("../../themes/first-backoffice/templates/page.login.user"),
      "section.admin.app-config-nav": () => import("../../themes/first-backoffice/templates/admin/section.admin.app-config-nav"),
      "section.admin.app-config-nav.item": () => import("../../themes/first-backoffice/templates/admin/section.admin.app-config-nav.item"),
      "section.admin.app-config-nav.panel": () => import("../../themes/first-backoffice/templates/admin/section.admin.app-config-nav.panel"),
      "section.admin.breadcrumb": () => import("../../themes/first-backoffice/templates/admin/section.admin.breadcrumb"),
      "section.admin.dashboard.module-widget": () => import("../../themes/first-backoffice/templates/admin/section.admin.dashboard.module-widget"),
      "section.admin.dashboard.overview": () => import("../../themes/first-backoffice/templates/admin/section.admin.dashboard.overview"),
      "section.admin.dashboard.quick-links": () => import("../../themes/first-backoffice/templates/admin/section.admin.dashboard.quick-links"),
      "section.admin.dashboard.recent-activity": () => import("../../themes/first-backoffice/templates/admin/section.admin.dashboard.recent-activity"),
      "section.admin.metrics-grid": () => import("../../themes/first-backoffice/templates/admin/section.admin.metrics-grid"),
      "section.admin.nav": () => import("../../themes/first-backoffice/templates/admin/section.admin.nav"),
      "section.admin.table.logs.cell": () => import("../../themes/first-backoffice/templates/admin/section.admin.table.logs.cell"),
      "section.admin.table.orders.cell": () => import("../../themes/first-backoffice/templates/admin/section.admin.table.orders.cell"),
      "section.admin.table.payments.cell": () => import("../../themes/first-backoffice/templates/admin/section.admin.table.payments.cell"),
      "section.admin.table.subscriptions.cell": () => import("../../themes/first-backoffice/templates/admin/section.admin.table.subscriptions.cell"),
      "section.admin.table.subscriptions.templates.cell": () => import("../../themes/first-backoffice/templates/admin/section.admin.table.subscriptions.templates.cell"),
      "section.admin.table.suscriptions.user.cell": () => import("../../themes/first-backoffice/templates/admin/section.admin.table.suscriptions.user.cell"),
      "section.admin.table.users.cell": () => import("../../themes/first-backoffice/templates/admin/section.admin.table.users.cell"),
      "section.dashboard.table.subscriptions.invoices.cell": () => import("../../themes/first-backoffice/templates/dashboard/section.dashboard.table.subscriptions.invoices.cell"),
      "section.dashboard.table.subscriptions.organizations.cell": () => import("../../themes/first-backoffice/templates/dashboard/section.dashboard.table.subscriptions.organizations.cell"),
      "section.dashboard.table.subscriptions.payments.cell": () => import("../../themes/first-backoffice/templates/dashboard/section.dashboard.table.subscriptions.payments.cell"),
      "system.not-found": () => import("../../themes/first-backoffice/templates/system.not-found"),
      "ui.alert-dialog": () => import("../../themes/first-backoffice/templates/ui.alert-dialog"),
      "ui.async-submit-button": () => import("../../themes/first-backoffice/templates/ui.async-submit-button"),
      "ui.dialog": () => import("../../themes/first-backoffice/templates/ui.dialog"),
      "ui.language-switcher": () => import("../../themes/first-backoffice/templates/ui.language-switcher"),
      "ui.table": () => import("../../themes/first-backoffice/templates/ui.table"),
      "ui.table.control": () => import("../../themes/first-backoffice/templates/ui.table.control"),
      "ui.theme-toggle": () => import("../../themes/first-backoffice/templates/ui.theme-toggle"),
      "ui.user-menu": () => import("../../themes/first-backoffice/templates/ui.user-menu"),
    },
  },
  "theme.first.frontend": {
    themeId: "theme.first.frontend",
    configImport: () => import("../../themes/first-frontend/config"),
    providerImport: () => import("../../themes/first-frontend/config").then(m => ({ default: m.default?.Provider ?? (({ children }: any) => children) })),
    templates: {
      "layout.frontend.shell": () => import("../../themes/first-frontend/templates/layout.frontend.shell"),
      "page.frontend.home": () => import("../../themes/first-frontend/templates/page.frontend.home"),
      "page.frontend.pricing": () => import("../../themes/first-frontend/templates/page.frontend.pricing"),
      "system.not-found": () => import("../../themes/first-frontend/templates/system.not-found"),
    },
  },
  "theme.pilot.admin": {
    themeId: "theme.pilot.admin",
    configImport: () => import("../../themes/pilot-admin/config"),
    providerImport: () => import("../../themes/pilot-admin/config").then(m => ({ default: m.default?.Provider ?? (({ children }: any) => children) })),
    templates: {
      "ui.table": () => import("../../themes/pilot-admin/templates/ui.table"),
    },
  },
  "theme.shadcn.dashboard.frontend": {
    themeId: "theme.shadcn.dashboard.frontend",
    configImport: () => import("../../themes/shadcn-dashboard-frontend/config"),
    providerImport: () => import("../../themes/shadcn-dashboard-frontend/config").then(m => ({ default: m.default?.Provider ?? (({ children }: any) => children) })),
    templates: {
      "layout.frontend.shell": () => import("../../themes/shadcn-dashboard-frontend/templates/layout.frontend.shell"),
      "page.frontend.home": () => import("../../themes/shadcn-dashboard-frontend/templates/page.frontend.home"),
      "page.frontend.pricing": () => import("../../themes/shadcn-dashboard-frontend/templates/page.frontend.pricing"),
      "system.not-found": () => import("../../themes/shadcn-dashboard-frontend/templates/system.not-found"),
    },
  },
};
